### PR TITLE
Allow user to define mPDF root path using environmental variables

### PR DESCRIPTION
**Pull request by jakejackson1**
Patch compliments https://github.com/mpdf/mpdf/pull/197

Note: had to fork current mpdf-examples and remove the Mpdf requirement from composer.json as couldn't resolve dependency issue using custom branch / PR. @finwe: we will need to correctly resolve this issue and then update the composer.json URLs referenced in https://github.com/mpdf/mpdf/pull/197/commits/116039e597c562a187e5479b4b148960647c4650

### CODE REVIEW

**Comment by jakejackson1** [comment]
I did additional research into this problem and while [circular dependencies in composer can work](https://github.com/composer/composer/issues/2234) they aren't practical. 

I suggest permanently removing the Mpdf composer requirement as I have done with this patch and instead provide appropriate documentation to correctly run the example files.

**Comment by finwe** [comment]
Sure, could you also prepare the doc PR? Thanks for this!

**Comment by jakejackson1** [comment]
I can. 

My thinking is the most appropriate place for this information would be in the Mpdf/Mpdf Readme.md file as a quick start guide. Or a dedicated page in the docs, but with a reference to it in the main Readme.md file. Which one should I do?

**Comment by finwe** [comment]
I'd go with a dedicated page in the docs and a reference on main Readme.

**Comment by jakejackson1** [comment]
I saw you had started on a v7 install page. Since the v6 install page references the example files I kept everything consistent and included the details on the v7 install page.

Since there should be a link to the installation docs in the Readme already (or will be eventually) I didn't bother updating that file as well.

**Comment by finwe** [comment]
This is on for a while already, closing.

**Pull request closed without merging**
